{% set name = "ogre" %}
{% set version = "1.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OGRECave/ogre.git
  git_rev: v{{ version }}
  patches:
    - 0001-enable-pkg-config-for-Windows.patch

build:
  number: 0
  skip: true  # [osx or win and vc<14]
  run_exports:
    - {{ pin_subpackage('ogre', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make  # [unix]
  host:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt  # [unix]
    - freetype
    - pugixml
  run:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt  # [unix]
    - freetype
    - pugixml

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\OgreMain.dll exit 1  # [win]

about:
  home: https://www.ogre3d.org/
  license: MIT
  license_file: LICENSE
  summary: 'OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
