{% set name = "ogre" %}
{% set version = "1.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OGRECave/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f35b67a8c70f48be714cb8a180af52ed1fbc0f773cf2918bbdd1116460d0129a
  patches:
    - 0001-enable-pkg-config-for-Windows.patch

build:
  number: 0
  skip: true  # [osx or win and vc<14]
  run_exports:
    - {{ pin_subpackage('ogre', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make  # [unix]
  host:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt  # [unix]
    - freetype  # [unix]
  run:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt  # [unix]
    - freetype  # [unix]

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\OgreMain.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://www.ogre3d.org/
  license: MIT
  license_file: LICENSE
  summary: 'OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
