{% set name = "ogre" %}
{% set version = "1.10.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OGRECave/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5b755a91bcb2a48a01c74109a9b41592533700622a8394c62589dce2adeddead
  patches:
      - 0001-enable-pkg-config-for-Windows.patch  # [win]
      - 0002-osx-no-framework.patch               # [osx]
      - 0003-arm-platform.patch                   # [arm64]

build:
  number: 8
  run_exports:
    - {{ pin_subpackage('ogre', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make                               # [unix]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
  host:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - libglu       # [linux]
    - freetype
    - pugixml
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2 2.0.12
    - swig         # [unix and not aarch64 and not ppc64le]
    - mono         # [unix and not aarch64 and not ppc64le and not arm64]
  run:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - freetype
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - swig         # [unix and not aarch64 and not ppc64le]

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\OgreMain.dll exit 1  # [win]
    - test -f $PREFIX/include/OGRE/OgreRoot.h  # [unix]
    - test -f $PREFIX/lib/pkgconfig/OGRE.pc  # [unix]
    - test -f $PREFIX/lib/libOgreMain${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/OGRE/cmake/OgreAddTargets.cmake  # [linux]
    - test -f $PREFIX/CMake/OgreAddTargets.cmake  # [osx]
    - test -f $PREFIX/lib/libOgreRTShaderSystem${SHLIB_EXT}  # [unix]

about:
  home: https://www.ogre3d.org/
  license: MIT
  license_file: LICENSE
  summary: 'OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
