{% set name = "ogre" %}
{% set version = "1.10.12" %}
# Workaround for https://github.com/conda/conda-libmamba-solver/issues/446
{% set conda_forge_specific_tweak_version = "1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.{{ conda_forge_specific_tweak_version }}

source:
  url: https://github.com/OGRECave/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5b755a91bcb2a48a01c74109a9b41592533700622a8394c62589dce2adeddead
  patches:
      - 0001-enable-pkg-config-for-Windows.patch  # [win]
      - 0002-osx-no-framework.patch               # [osx]
      - 0003-arm-platform.patch                   # [arm64]
      - 0004-fix-new-libcxx.patch
      - 0005-drop-std-binary-function.patch

build:
  number: 9
  run_exports:
    - {{ pin_subpackage('ogre', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake 3.25
    - pkg-config
    - make            # [unix]
  host:
    - libgl-devel     # [linux]
    - xorg-libx11     # [unix]
    - xorg-libxaw     # [unix]
    - xorg-libxt      # [unix]
    - xorg-libxrandr  # [unix]
    - libglu          # [linux]
    - freetype
    - pugixml
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2 2.0.12
    - swig         # [unix and not aarch64 and not ppc64le]
    - mono         # [unix and not aarch64 and not ppc64le and not arm64]
  run:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - freetype
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - swig         # [unix and not aarch64 and not ppc64le]

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\OgreMain.dll exit 1  # [win]
    - test -f $PREFIX/include/OGRE/OgreRoot.h  # [unix]
    - test -f $PREFIX/lib/pkgconfig/OGRE.pc  # [unix]
    - test -f $PREFIX/lib/libOgreMain${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/OGRE/cmake/OgreAddTargets.cmake  # [linux]
    - test -f $PREFIX/CMake/OgreAddTargets.cmake  # [osx]
    - test -f $PREFIX/lib/libOgreRTShaderSystem${SHLIB_EXT}  # [unix]

about:
  home: https://www.ogre3d.org/
  license: MIT
  license_file: LICENSE
  summary: 'OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
    - traversaro
