{% set name = "ogre" %}
{% set version = "14.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/OGRECave/ogre/archive/v{{ version }}.tar.gz
    sha256: 5a25357a8d8423f9fd8a06e0f46abeba932e6093f402d08cc5d3249c1ce40109
    patches:
      - 0001-enable-pkg-config-for-Windows.patch  # [win]
      - 0002-osx-no-framework.patch  # [osx]
      - 0003-clang11-fix.patch  # [osx]
      - 0004-fix-glx.patch  # [linux]
  - url: https://github.com/ocornut/imgui/archive/v1.73.tar.gz
    sha256: 4c7255f49d814a389c23d170ac4f25dfe9b84a392307b92abc77fa63114ce2b5
    folder: Components/Overlay/src/imgui/

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('ogre', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make  # [unix]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
  host:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - libglu       # [linux]
    - freetype
    - pugixml
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - numpy
    - swig 4.0     # [unix and not aarch64 and not ppc64le]
    - mono         # [unix and not aarch64 and not ppc64le and not arm64]
    - bullet-cpp
    - assimp
  run:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - freetype
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - {{ pin_compatible('numpy') }}
    - lxml
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\OgreMain.dll exit 1  # [win]
    - test -f $PREFIX/include/OGRE/OgreRoot.h  # [unix]
    - test -f $PREFIX/lib/pkgconfig/OGRE.pc  # [unix]
    - test -f $PREFIX/lib/libOgreMain${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libOgreRTShaderSystem${SHLIB_EXT}  # [unix]

about:
  home: https://www.ogre3d.org/
  license: MIT
  license_file: LICENSE
  summary: OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
