{% set name = "ogre" %}
{% set version = "1.12.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/OGRECave/ogre/archive/v{{ version }}.tar.gz
    sha256: 8866a6ab32c424f4ecf53f452f5c2812f35b6643ed18266eb26c607d8b2f5eb5
    patches:
      - 0001-enable-pkg-config-for-Windows.patch  # [win]
      - 0002-osx-no-framework.patch  # [osx]
  - url: https://github.com/ocornut/imgui/archive/v1.73.tar.gz
    sha256: 4c7255f49d814a389c23d170ac4f25dfe9b84a392307b92abc77fa63114ce2b5
    folder: Components/Overlay/src/imgui/

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('ogre', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make  # [unix]
    - {{ cdt('xorg-x11-proto-devel') }}  # [unix]
    - {{ cdt('mesa-libgl-devel') }}      # [unix]
    - {{ cdt('mesa-dri-drivers') }}      # [unix]
    - {{ cdt('libxrender-devel') }}      # [unix]
    - {{ cdt('libxrandr-devel') }}       # [unix]
    - {{ cdt('libxrandr') }}             # [unix]
  host:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - libglu       # [linux]
    - freetype
    - pugixml
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - swig         # [unix]
    - mono         # [unix]
  run:
    - xorg-libx11  # [unix]
    - xorg-libxaw  # [unix]
    - xorg-libxt   # [unix]
    - freetype
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - swig         # [unix]

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\OgreMain.dll exit 1  # [win]

about:
  home: https://www.ogre3d.org/
  license: MIT
  license_file: LICENSE
  summary: OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
