context:
  name: ogre
  version: 14.3.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/OGRECave/ogre/archive/v${{ version }}.tar.gz
    sha256: a3a052dc14e7ce273e86e18c900be4b8c35f9b90bd4613843dc18b0650b19ae2
    patches:
      - if: win
        then: 0001-enable-pkg-config-for-Windows.patch
      - if: osx
        then: 0002-osx-no-framework.patch
      - if: osx
        then: 0003-clang11-fix.patch
      - if: linux
        then: 0004-fix-glx.patch
  - url: https://github.com/ocornut/imgui/archive/v1.73.tar.gz
    sha256: 4c7255f49d814a389c23d170ac4f25dfe9b84a392307b92abc77fa63114ce2b5
    target_directory: Components/Overlay/src/imgui/

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - pkg-config
    - if: unix
      then: make
    - if: linux
      then: ${{ cdt('xorg-x11-proto-devel') }}
    - if: linux
      then: ${{ cdt('mesa-libgl-devel') }}
    - if: linux
      then: ${{ cdt('mesa-dri-drivers') }}
    - if: linux
      then: ${{ cdt('libxrender-devel') }}
    - if: linux
      then: ${{ cdt('libxrandr-devel') }}
    - if: linux
      then: ${{ cdt('libxrandr') }}
  host:
    - if: unix
      then: xorg-libx11
    - if: unix
      then: xorg-libxaw
    - if: unix
      then: xorg-libxt
    - if: linux
      then: libglu
    - freetype
    - pugixml
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - numpy
    - if: unix and not aarch64 and not ppc64le or unix and not aarch64 and not ppc64le
      then: swig 4.0.*
    - if: unix and not aarch64 and not ppc64le and not arm64
      then: mono
    - bullet-cpp
    - assimp
  run:
    - if: unix
      then: xorg-libx11
    - if: unix
      then: xorg-libxaw
    - if: unix
      then: xorg-libxt
    - freetype
    - zlib
    - zziplib
    - freeimage
    - openexr
    - sdl2
    - ${{ pin_compatible('numpy') }}
    - lxml
  run_exports:
    - ${{ pin_subpackage('ogre', upper_bound='x.x') }}

tests:
  - script:
      - if: win
        then: if not exist %PREFIX%\\Library\\bin\\OgreMain.dll exit 1
      - if: unix
        then: test -f $PREFIX/include/OGRE/OgreRoot.h
      - if: unix
        then: test -f $PREFIX/lib/pkgconfig/OGRE.pc
      - if: unix
        then: test -f $PREFIX/lib/libOgreMain${SHLIB_EXT}
      - if: unix
        then: test -f $PREFIX/lib/libOgreRTShaderSystem${SHLIB_EXT}

about:
  license: MIT
  license_file: LICENSE
  summary: OGRE is a scene-oriented, flexible 3D engine written in C++ designed to make it easier and more intuitive for developers to produce games and demos utilising 3D hardware.
  homepage: https://www.ogre3d.org/

extra:
  recipe-maintainers:
    - traversaro
    - seanyen
    - wolfv
    - Tobias-Fischer
